[project]
name = "stock-predict"
version = "0.1.0"
description = "Sistema de predição inteligente no controle de estoque"
readme = "README.md"
authors = [
    { name = "João Vítor Florão" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "reflex>=0.9.8",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
stock-predict = "stock_predict:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
