"""create items and movements tables

Revision ID: 326036c2a548
Revises: 
Create Date: 2026-08-16 18:26:06.434948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326036c2a548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_item_external_id'), 'stock_item', ['external_id'], unique=True)
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'SALE', 'CONSUME', name='movementtype'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['stock_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_date'), 'stock_movement', ['date'], unique=False)
    op.create_index(op.f('ix_stock_movement_item_id'), 'stock_movement', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movement_item_id'), table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_date'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_stock_item_external_id'), table_name='stock_item')
    op.drop_table('stock_item')
    # ### end Alembic commands ###
